### ISSUE TITLE
IE11 issue with matches function

### ISSUE THREAD

**Issue by mattnortham** [ryanmaffey/password-strength-utility#1]
![screen shot 2017-09-11 at 10 14 01](https://user-images.githubusercontent.com/4312999/30267295-f88c199e-96d9-11e7-8dba-535c26dc9576.png)

Appears to be resolved with a polyfill
`// Polyfill to handle matches on IE9+
// as per https://developer.mozilla.org/en-US/docs/Web/API/Element/matches
if (!Element.prototype.matches)
    Element.prototype.matches =
        Element.prototype.msMatchesSelector ||
        Element.prototype.webkitMatchesSelector;`

**Comment by ryanmaffey** [comment]
Thanks you @mattnortham - that should now be fixed in v. 1.1.6. I also didn't realise that there was an issue with IE not properly supporting CustomEvents so that has also been fixed in the latest version.
